# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.zfs.devNodes = "/dev/disk/by-id";

  fileSystems."/" =
    {
      device = "phoenix-pool/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "phoenix-pool/nix";
      fsType = "zfs";
    };

  fileSystems."/var" =
    {
      device = "phoenix-pool/var";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "phoenix-pool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-id/ata-SSDPR-CX400-256-G2_360055473-part1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [{
      device = "/dev/disk/by-id/ata-SSDPR-CX400-256-G2_360055473-part2";
      randomEncryption = true;
    }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
